# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate_baseline"
evaluate: true
# in evaluate mode, must give these params!!!!!
evaluate_psro_dir: /home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-19_22-38-12
evaluate_savedir: "/home/panpan/acces_games/logs/train/runs/acsp50/am-acsp50/2024-05-22_19-57-54"
ckpt_path: /home/panpan/acces_games/logs/train/runs/acsp50/am-acsp50/2024-05-22_19-57-54/rl4co/c1b28edi/checkpoints/epoch=0-step=20.ckpt
#/home/panpan/rl4co/logs/train/runs/pg50/am-pg50/2024-05-20_18-03-16/rl4co/k3zk6zju/checkpoints/epoch=199-step=4000.ckpt
#/home/panpan/rl4co/logs/train/runs/pg50/am-pg50/2024-05-20_18-03-16/rl4co/k3zk6zju/checkpoints/epoch=199-step=4000.ckpt
#/home/panpan/rl4co/logs/train/runs/pg20/am-pg20/2024-05-20_14-02-31/rl4co/x8nylfz3/checkpoints/epoch=99-step=2000.ckpt
#/home/panpan/rl4co/logs/train/runs/csp20/am-csp20/2024-05-20_03-41-40/rl4co/v9xuiw1j/checkpoints/epoch=99-step=2000.ckpt
#"/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/rl4co/hnwv41v5/checkpoints/epoch=49-step=1000.ckpt"
evaluate_loc: "${evaluate_savedir}"
baseline: "LS2"   # ["cw", "tabu"] for acvrp; ["LS1", "LS2"] or acsp; ["LS", "greedy_op"] for pg

