# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

evaluate_baseline: true
# in evaluate mode, must give these params!!!!!
# evaluate_savedir: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33"
# ckpt_path: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33/rl4co/mql00v5r/checkpoints/epoch=2-step=3.ckpt"
evaluate_savedir: "/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21/"
ckpt_path: "/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21/rl4co/ajzphdl4/checkpoints/epoch=99-step=250000.ckpt"
evaluate_loc: "${evaluate_savedir}"
baseline: "tabu"   # ["cw", "tabu"] for svrp

