# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate_other"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
eval_otherprog_with_psroadv: true

# 要加载的psro的模型的位置
evaluate_savedir: "/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-05_16-14-06"
npz_pth: "/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-05_16-14-06/psro/info.npz"


## eval rl
eval_rl_prog: false
# rl
rl_prog_dir: "/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21"
rl_prog_pth: "/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21/rl4co/ajzphdl4/checkpoints/epoch=99-step=250000.ckpt"

## eval baseline
eval_baseline_prog: true
baseline_heur: "tabu"   # "cw"
ckpt_psro_path: "/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-05_16-14-06"

