# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate_other"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
eval_otherprog_with_psroadv: true

# run_psroadv_eval.py
# 要加载的psro的模型的位置
# svrp20-1:
# /home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-07_21-21-53
# svrp20-2:
# /home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-07_21-36-12
# csp20-1
# /home/panpan/rl4co/logs/train_psro/runs/csp20/am-csp20/2024-05-06_10-43-24
# csp20-2
# /home/panpan/rl4co/logs/train_psro/runs/csp20/am-csp20/2024-05-07_14-56-15
# opsa20-1_old
# /home/panpan/rl4co/logs/train_psro/runs/opsa20/am-opsa20/2024-05-09_09-25-21
# opsa20-2_old
# /home/panpan/rl4co/logs/train_psro/runs/opsa20/am-opsa20/2024-05-09_17-39-26
# opsa20-1
# /home/panpan/rl4co/logs/train_psro/runs/opsa20/am-opsa20/2024-05-11_22-31-01
# csp20new
# /home/panpan/rl4co/logs/train_psro/runs/csp20/am-csp20/2024-05-13_23-12-14
# svrp50
# /home/panpan/rl4co/logs/train/runs/svrp50/am-svrp50/2024-05-04_22-56-20
# new
# /home/panpan/rl4co/logs/train_psro/runs/csp20/am-csp20/2024-05-17_22-22-56
# "/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-16_16-38-09"

evaluate_adv_dir: /home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-19_22-38-12
adv_npz_pth: "/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-19_22-38-12/psro/info.npz"
ckpt_psro_path: /home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-19_22-38-12
#/home/panpan/rl4co/logs/train_psro/runs/csp20/am-csp20/2024-05-20_03-59-47
#/home/panpan/rl4co/logs/train_psro/runs/opsa50/am-opsa50/2024-05-20_21-15-34
#/home/panpan/rl4co/logs/train_psro/runs/opsa20/am-opsa20/2024-05-20_04-36-49
#"/home/panpan/rl4co/logs/train_psro/runs/svrp20/am-svrp20/2024-05-19_22-38-12"

## eval rl
eval_rl_prog: false
# rl
rl_prog_dir: /home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/
rl_prog_pth: /home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/rl4co/hnwv41v5/checkpoints/epoch=49-step=1000.ckpt
#/home/panpan/rl4co/logs/train/runs/opsa50/am-opsa50/2024-05-20_18-03-16/rl4co/k3zk6zju/checkpoints/epoch=199-step=4000.ckpt
#/home/panpan/rl4co/logs/train/runs/csp20/am-csp20/2024-05-20_03-41-40/rl4co/v9xuiw1j/checkpoints/epoch=99-step=2000.ckpt
#/home/panpan/rl4co/logs/train/runs/opsa20/am-opsa20/2024-05-20_04-17-16/rl4co/nwo4bjx8/checkpoints/epoch=99-step=2000.ckpt
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/rl4co/hnwv41v5/checkpoints/epoch=49-step=1000.ckpt
# no stoch
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_20-56-05/rl4co/6bib2wms/checkpoints/epoch=49-step=1000.ckpt
# sotch
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/rl4co/hnwv41v5/checkpoints/epoch=49-step=1000.ckpt
# /home/panpan/rl4co/logs/train/runs/opsa20/am-opsa20/2024-05-08_09-14-24/rl4co/cks8a5wy/checkpoints/epoch=99-step=125000.ckpt
# /home/panpan/rl4co/logs/train/runs/svrp50/am-svrp50/2024-05-04_22-56-20/rl4co/n4no1ty5/checkpoints/epoch=99-step=125000.ckpt
# opsa50-data0
#/home/panpan/rl4co/logs/train/runs/opsa50/am-opsa50/2024-05-08_05-17-10/rl4co/j8nwkpj1/checkpoints/epoch=99-step=125000.ckpt
#/home/panpan/rl4co/logs/train/runs/csp20/am-csp20/2024-04-25_14-06-46/rl4co/u9r7s1o3/checkpoints/epoch=99-step=125000.ckpt
#"/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21/rl4co/ajzphdl4/checkpoints/epoch=99-step=250000.ckpt"

## eval baseline
eval_baseline_prog: true
baseline_heur: "tabu"   # ["cw", "tabu"] for svrp; ["LS1", "LS2"] or csp


