# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
evaluate: true

evaluate_savedir: "/home/panpan/rl4co/logs/train/runs/opsa20/am-opsa20/2024-05-20_01-52-52/"
ckpt_path: /home/panpan/rl4co/logs/train/runs/opsa20/am-opsa20/2024-05-20_01-52-52/rl4co/qy23fvab/checkpoints/epoch=49-step=1000.ckpt
# nstohc
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_20-56-05/rl4co/6bib2wms/checkpoints/epoch=49-step=1000.ckpt
# stoch
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-19_17-43-10/rl4co/hnwv41v5/checkpoints/epoch=49-step=1000.ckpt
#new
#/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-16_11-37-16/rl4co/x80zwa1a/checkpoints/epoch=99-step=62500.ckpt
########
# opsa50-data0
#/home/panpan/rl4co/logs/train/runs/opsa50/am-opsa50/2024-05-08_05-17-10/rl4co/j8nwkpj1/checkpoints/epoch=99-step=125000.ckpt
#"/home/panpan/rl4co/logs/train/runs/csp50/am-csp50/2024-05-04_07-06-59/rl4co/9rwb952x/checkpoints/epoch=99-step=125000.ckpt"
# svrp20-data0
#"/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-02-27_12-22-21/rl4co/ajzphdl4/checkpoints/epoch=99-step=250000.ckpt"
# svrp20-data1
#"/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-05-08_21-14-27/rl4co/sgtdk5tf/checkpoints/epoch=99-step=125000.ckpt"
evaluate_loc: "${evaluate_savedir}"
evaluate_method: "greedy"   # ["greedy", "sampling", "greedy_multistart", "augment_dihedral_8", "augment", "greedy_multistart_augment_dihedral_8", "greedy_multistart_augment"]

