_target_: rl4co.models.AttentionModel

policy:
  _target_: rl4co.models.AttentionModelPolicy
  env: ${env}
  embedding_dim: 128

baseline:
  _target_: rl4co.models.rl.reinforce.WarmupBaseline
  baseline:
    _target_: rl4co.models.rl.reinforce.RolloutBaseline
