_target_: ncobench.models.am.AttentionModel

policy:
  _target_: ncobench.models.components.am.base.AttentionModelBase
  env: ${env}
  embedding_dim: 128
  hidden_dim: 128

baseline:
  _target_: ncobench.models.rl.reinforce.WarmupBaseline
  baseline:
    _target_: ncobench.models.rl.reinforce.RolloutBaseline
