_target_: rl4co.models.HeterogeneousAttentionModel

policy:
  _target_: rl4co.models.HeterogeneousAttentionModelPolicy
  env: ${env}
  embedding_dim: 128
  hidden_dim: 128

baseline:
  _target_: rl4co.models.rl.reinforce.WarmupBaseline
  baseline:
    _target_: rl4co.models.rl.reinforce.RolloutBaseline
