defaults:
  # - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - speed_monitor.yaml
  - learning_rate_monitor.yaml
  - _self_



model_summary:
  max_depth: 5 # change to -1 to show all. 5 strikes a good balance between readability and completeness
