_target_: rl4co.envs.CSPEnv
name: csp

num_loc: 20
min_cover: 0.
max_cover: 0.25
stoch_idx: ${paths.stoch_idx}   # for stoch model params
data_dir: ${paths.root_dir}/data${paths.stoch_idx}/csp
val_file: csp${env.num_loc}_val_seed4321_size10000.npz
test_file: csp${env.num_loc}_test_seed1234_size100.npz