_target_: rl4co.envs.OPSAEnv
name: opsa

num_loc: 20

stoch_idx: ${paths.stoch_idx}   # for stoch model params
data_dir: ${paths.root_dir}/data${paths.stoch_idx}/opsa
dataset_flag: "val"
# train_file: svrp_}${env.num_loc}_val_seed4321_size${model.val_data_size}.npz

val_file: opsa${env.num_loc}_val.npz
test_file: opsa${env.num_loc}_test.npz