_target_: rl4co.envs.OPSAEnv
name: opsa

num_loc: 20

stoch_idx: ${paths.stoch_idx}   # for stoch model params
data_dir: ${paths.root_dir}/data${paths.stoch_idx}/opsa
val_file: opsa${env.num_loc}_val.npz
test_file: opsa${env.num_loc}_test.npz