_target_: rl4co.envs.SVRPEnv
name: svrp

num_loc: 20

stoch_idx: ${paths.stoch_idx}   # for stoch model params
data_dir: ${paths.root_dir}/data${paths.stoch_idx}/svrp
val_file: svrp_modelize${env.num_loc}_val_seed4321_size10000.npz
test_file: svrp_modelize${env.num_loc}_test_seed1234_size100.npz