_target_: rl4co.envs.SVRPEnv
name: svrp

num_loc: 20
generate_method: "modelize"   # ["uniform", "modelize", "no_stoch"]
stoch_idx: ${paths.stoch_idx}   # for stoch model params
data_dir: ${paths.root_dir}/data${paths.stoch_idx}/svrp
train_file: svrp_${env.generate_method}${env.num_loc}_val_seed4321_size${model.val_data_size}.npz

# 在哪个数据集上eval
eval_dataset: "val" # "val"    
# 是否对该数据集进行sample
dataset_state: "sample" # "no_sample"
dataset_flag: ${env.eval_dataset}_${env.dataset_state}  #"val_sample"        #"test"   # "val"

val_file: svrp_${env.generate_method}${env.num_loc}_val_seed4321_size${model.val_data_size}.npz
test_file: svrp_${env.generate_method}${env.num_loc}_test_seed1234_size${model.test_data_size}.npz
# svrp_modelize${env.num_loc}_test_seed1234_size100.npz